// @/database/grammar/tenses.ts
import { GrammarQuestion } from '../../types';

export const tenses: GrammarQuestion[] = [
    // ==============================================================================
    // --- EASY ---
    // ==============================================================================
    { question: 'I ___ to the store yesterday.', options: ['went', 'go', 'have gone', 'am going'], correctAnswer: 'went', explanation: 'The word "yesterday" indicates that the action happened in the past, so the simple past tense "went" is correct.', difficulty: 'Easy' },
    { question: 'She ___ her homework right now.', options: ['is doing', 'does', 'did', 'has done'], correctAnswer: 'is doing', explanation: '"Right now" indicates an action in progress, requiring the present continuous tense.', difficulty: 'Easy' },
    { question: 'What ___ you do last weekend?', options: ['did', 'do', 'have', 'were'], correctAnswer: 'did', explanation: '"Did" is the auxiliary verb for questions in the past simple.', difficulty: 'Easy' },
    { question: 'Look! The bus ___.', options: ['comes', 'is coming', 'came', 'will come'], correctAnswer: 'is coming', explanation: 'We use Present Continuous for things happening at the moment of speaking.', difficulty: 'Easy' },
    { question: 'Water ___ at 100 degrees Celsius.', options: ['boils', 'is boiling', 'boiled', 'boil'], correctAnswer: 'boils', explanation: 'We use Present Simple for scientific facts and general truths.', difficulty: 'Easy' },
    { question: '___ you ever been to Japan?', options: ['Did', 'Have', 'Do', 'Were'], correctAnswer: 'Have', explanation: 'Present Perfect is used for life experiences ("Have you ever...").', difficulty: 'Easy' },
    { question: 'They ___ football every Sunday.', options: ['play', 'playing', 'are playing', 'have played'], correctAnswer: 'play', explanation: 'Present Simple is used for regular habits or routines.', difficulty: 'Easy' },
    { question: 'I ___ hungry.', options: ['am', 'have', 'do', 'will'], correctAnswer: 'am', explanation: 'Use the verb "to be" (am) with adjectives like "hungry".', difficulty: 'Easy' },
    { question: 'He ___ work at 9 AM yesterday.', options: ['start', 'started', 'starts', 'is starting'], correctAnswer: 'started', explanation: 'Simple Past is used for a finished action at a specific time in the past.', difficulty: 'Easy' },
    { question: 'We ___ to the cinema tonight.', options: ['go', 'are going', 'went', 'have gone'], correctAnswer: 'are going', explanation: 'Present Continuous can be used for fixed future arrangements.', difficulty: 'Easy' },
    { question: 'Where ___ she live?', options: ['do', 'does', 'is', 'has'], correctAnswer: 'does', explanation: 'Present Simple questions with he/she/it use the auxiliary "does".', difficulty: 'Easy' },
    { question: 'I ___ my teeth twice a day.', options: ['brush', 'brushing', 'brushes', 'brushed'], correctAnswer: 'brush', explanation: 'Use Present Simple for daily routines.', difficulty: 'Easy' },
    { question: '___ they watching TV?', options: ['Do', 'Are', 'Have', 'Will'], correctAnswer: 'Are', explanation: 'Present Continuous questions start with the verb "to be" (Are).', difficulty: 'Easy' },
    { question: 'He ___ like pizza.', options: ['don\'t', 'doesn\'t', 'isn\'t', 'hasn\'t'], correctAnswer: 'doesn\'t', explanation: 'Negative Present Simple with he/she/it uses "doesn\'t".', difficulty: 'Easy' },
    { question: 'I ___ a letter when you called.', options: ['wrote', 'was writing', 'write', 'have written'], correctAnswer: 'was writing', explanation: 'Past Continuous describes a longer action interrupted by a shorter one.', difficulty: 'Easy' },

    // ==============================================================================
    // --- MEDIUM ---
    // ==============================================================================
    { question: 'I ___ my keys. I can\'t find them anywhere.', options: ['lost', 'have lost', 'had lost', 'am losing'], correctAnswer: 'have lost', explanation: 'Present perfect is used for a past action with a present result.', difficulty: 'Medium' },
    { question: 'By the time I arrived, he ___', options: ['already left', 'had already left', 'has already left', 'left'], correctAnswer: 'had already left', explanation: 'Past perfect is used for an action that happened before another past action.', difficulty: 'Medium' },
    { question: 'He ___ in this city since 2010.', options: ['lives', 'is living', 'has lived', 'lived'], correctAnswer: 'has lived', explanation: 'Present perfect is used for an action that started in the past and continues to the present.', difficulty: 'Medium' },
    { question: 'I ___ for you for two hours!', options: ['waited', 'am waiting', 'have been waiting', 'wait'], correctAnswer: 'have been waiting', explanation: 'Present perfect continuous emphasizes the duration of an action that started in the past and continues to the present.', difficulty: 'Medium' },
    { question: 'When I was a child, I ___ to play outside every day.', options: ['used', 'use', 'was using', 'have used'], correctAnswer: 'used', explanation: '"Used to" describes past habits that are no longer true.', difficulty: 'Medium' },
    { question: 'She ___ English for five years.', options: ['studies', 'is studying', 'has been studying', 'studied'], correctAnswer: 'has been studying', explanation: 'Present perfect continuous is used for an action over a period of time up to the present.', difficulty: 'Medium' },
    { question: 'While I ___ TV, the lights went out.', options: ['watched', 'was watching', 'am watching', 'watch'], correctAnswer: 'was watching', explanation: 'Past Continuous is used for an action in progress interrupted by a Past Simple action.', difficulty: 'Medium' },
    { question: 'I ___ her before.', options: ['have met', 'meet', 'meeting', 'have meet'], correctAnswer: 'have met', explanation: 'Present Perfect describes an experience in the past without a specific time.', difficulty: 'Medium' },
    { question: 'It ___ since this morning.', options: ['is raining', 'rains', 'has been raining', 'rained'], correctAnswer: 'has been raining', explanation: 'Present Perfect Continuous for an action starting in the past and continuing now.', difficulty: 'Medium' },
    { question: 'The movie ___ by the time we got to the cinema.', options: ['started', 'had started', 'has started', 'starts'], correctAnswer: 'had started', explanation: 'Past Perfect happens before another action in the past.', difficulty: 'Medium' },
    { question: 'I ___ lunch when the phone rang.', options: ['had', 'was having', 'have had', 'am having'], correctAnswer: 'was having', explanation: 'Past Continuous for an action in progress in the past.', difficulty: 'Medium' },
    { question: 'Don\'t call me at 8 PM. I ___ dinner.', options: ['will have', 'will be having', 'have', 'had'], correctAnswer: 'will be having', explanation: 'Future Continuous for an action in progress at a specific time in the future.', difficulty: 'Medium' },
    { question: 'We ___ just finished our homework.', options: ['have', 'did', 'were', 'had'], correctAnswer: 'have', explanation: '"Just" is often used with Present Perfect to show a very recent completion.', difficulty: 'Medium' },
    { question: 'While she ___ the book, she fell asleep.', options: ['read', 'was reading', 'has read', 'is reading'], correctAnswer: 'was reading', explanation: 'Two actions in the past: one long (reading) interrupted by a short one (fell asleep).', difficulty: 'Medium' },
    { question: 'I ___ him for ten years.', options: ['know', 'am knowing', 'have known', 'knew'], correctAnswer: 'have known', explanation: 'Stative verbs (like "know") are not usually used in continuous forms; use Present Perfect for duration.', difficulty: 'Medium' },

    // ==============================================================================
    // --- HARD ---
    // ==============================================================================
    { question: 'The train ___ at 10 AM tomorrow.', options: ['arrives', 'will arrive', 'is arriving', 'arrived'], correctAnswer: 'arrives', explanation: 'Simple present is used for scheduled future events (timetables).', difficulty: 'Hard' },
    { question: 'By next year, I ___ my studies.', options: ['will finish', 'will be finishing', 'will have finished', 'finish'], correctAnswer: 'will have finished', explanation: 'Future perfect is used for an action that will be completed before a certain time in the future.', difficulty: 'Hard' },
    { question: 'This time next week, I ___ on a beach.', options: ['will sit', 'will be sitting', 'sit', 'sat'], correctAnswer: 'will be sitting', explanation: 'Future Continuous describes an action in progress at a specific time in the future.', difficulty: 'Hard' },
    { question: 'How long ___ each other when they got married?', options: ['did they know', 'have they known', 'had they known', 'do they know'], correctAnswer: 'had they known', explanation: 'Past Perfect is used to ask about the duration of an action up to a specific point in the past.', difficulty: 'Hard' },
    { question: 'By the end of this month, we ___ here for ten years.', options: ['will live', 'will have lived', 'live', 'are living'], correctAnswer: 'will have lived', explanation: 'Future Perfect expresses an action completed (or duration achieved) before a future time.', difficulty: 'Hard' },
    { question: 'I ___ to the cinema three times this week.', options: ['went', 'have been', 'go', 'was going'], correctAnswer: 'have been', explanation: 'Present Perfect is used when the time period (this week) is not yet finished.', difficulty: 'Hard' },
    { question: 'I wish I ___ harder for the exam.', options: ['study', 'studied', 'had studied', 'have studied'], correctAnswer: 'had studied', explanation: '"I wish" + Past Perfect expresses a regret about the past.', difficulty: 'Hard' },
    { question: 'Hardly ___ the house when it started to rain.', options: ['I left', 'did I leave', 'had I left', 'have I left'], correctAnswer: 'had I left', explanation: 'Inversion with "Hardly" requires Past Perfect (Hardly had I left...).', difficulty: 'Hard' },
    { question: 'He is always ___ his keys!', options: ['lose', 'losing', 'lost', 'loses'], correctAnswer: 'losing', explanation: 'Present Continuous with "always" expresses annoyance at a repeated habit.', difficulty: 'Hard' },
    { question: 'When I arrive, they ___ for me.', options: ['will wait', 'will be waiting', 'wait', 'have waited'], correctAnswer: 'will be waiting', explanation: 'Future Continuous predicts an action already in progress at the time of arrival.', difficulty: 'Hard' },
    { question: 'After he ___ his breakfast, he went to work.', options: ['eats', 'has eaten', 'had eaten', 'was eating'], correctAnswer: 'had eaten', explanation: 'Past Perfect emphasizes that one action finished before the next one started.', difficulty: 'Hard' },
    { question: 'It’s time we ___ home.', options: ['go', 'went', 'have gone', 'will go'], correctAnswer: 'went', explanation: 'The phrase "It\'s time" is followed by the Past Simple (unreal past).', difficulty: 'Hard' },
    { question: 'She admitted that she ___ the money.', options: ['stole', 'has stolen', 'had stolen', 'steals'], correctAnswer: 'had stolen', explanation: 'Reported speech: simple past shifts to past perfect.', difficulty: 'Hard' },
    { question: 'I ___ to tell you the truth.', options: ['mean', 'am meaning', 'have been meaning', 'was meaning'], correctAnswer: 'have been meaning', explanation: 'Present Perfect Continuous expresses an intention that has existed for some time.', difficulty: 'Hard' },
    { question: 'The phone ___ constantly all morning.', options: ['rang', 'has been ringing', 'rings', 'is ringing'], correctAnswer: 'has been ringing', explanation: 'Present Perfect Continuous emphasizes the repetition and duration of the action up to now.', difficulty: 'Hard' },

    // ==============================================================================
    // --- EXAM ---
    // ==============================================================================
    { question: 'He ___ for the company for ten years when he retired.', options: ['worked', 'was working', 'had been working', 'has worked'], correctAnswer: 'had been working', explanation: 'Past perfect continuous is used to describe an ongoing action that was in progress before another past event.', difficulty: 'Exam' },
    { question: 'It is the first time I ___ sushi.', options: ['eat', 'am eating', 'have eaten', 'ate'], correctAnswer: 'have eaten', explanation: 'With the phrase "It is the first/second/best time...", we always use the Present Perfect.', difficulty: 'Exam' },
    { question: 'No sooner ___ the room than the lights went out.', options: ['I entered', 'did I enter', 'had I entered', 'have I entered'], correctAnswer: 'had I entered', explanation: '"No sooner" requires inversion with the Past Perfect.', difficulty: 'Exam' },
    { question: 'By the time you get this letter, I ___.', options: ['will leave', 'leave', 'will have left', 'am leaving'], correctAnswer: 'will have left', explanation: 'Future Perfect describes an action that will be finished before a specific future moment.', difficulty: 'Exam' },
    { question: 'I would rather you ___ that.', options: ['don\'t do', 'didn\'t do', 'not do', 'won\'t do'], correctAnswer: 'didn\'t do', explanation: '"I would rather" + person + Past Tense is used to express preference about someone else\'s action.', difficulty: 'Exam' },
    { question: 'Scarcely ___ started speaking when he was interrupted.', options: ['he had', 'had he', 'did he', 'has he'], correctAnswer: 'had he', explanation: 'Inversion with "Scarcely" + Past Perfect.', difficulty: 'Exam' },
    { question: 'They ___ on the project for months before they cancelled it.', options: ['worked', 'have worked', 'had been working', 'were working'], correctAnswer: 'had been working', explanation: 'Past Perfect Continuous emphasizes the duration of an activity before a past event.', difficulty: 'Exam' },
    { question: 'By 2030, scientists ___ a cure for the common cold.', options: ['discover', 'will discover', 'will have discovered', 'are discovering'], correctAnswer: 'will have discovered', explanation: 'Future Perfect is used for accomplishments expected by a certain date.', difficulty: 'Exam' },
    { question: 'Not until yesterday ___ the truth.', options: ['I heard', 'did I hear', 'had I heard', 'have I heard'], correctAnswer: 'did I hear', explanation: 'Inversion after negative adverbial phrases ("Not until...").', difficulty: 'Exam' },
    { question: '___ been informed earlier, I would have attended.', options: ['If', 'Had I', 'Have I', 'Did I'], correctAnswer: 'Had I', explanation: 'Inverted Third Conditional (Had I been informed = If I had been informed).', difficulty: 'Exam' },
    { question: 'She looks as if she ___ a ghost.', options: ['sees', 'has seen', 'had seen', 'saw'], correctAnswer: 'had seen', explanation: '"As if" + Past Perfect indicates an unreal comparison to a past event.', difficulty: 'Exam' },
    { question: 'They will be tired when they arrive because they ___ for 24 hours.', options: ['will travel', 'will have been traveling', 'are traveling', 'have traveled'], correctAnswer: 'will have been traveling', explanation: 'Future Perfect Continuous emphasizes the duration of an action at a future point in time.', difficulty: 'Exam' }
];